### ISSUE TITLE
FRMS/infra-chart not updating via helm repo update

### ISSUE THREAD

**Issue by Justus-Ortlepp-frms** [frmscoe/General-Issues#63]
### Summary

The latest changes to the FRMS/infra-chart/values.yaml file do not update when the repo is updated via the helm repo update command.

### Expected behaviour

After running the helm repo update command, the helm show all FRMS/infra-chart is expected to display the following:

`C:\>helm show all FRMS/infra-chart`

```
apiVersion: v2
description: A Helm chart for installing infrastructure components for the FRMS system.
name: infra-chart
type: application
version: 1.0.0

---
namespaces:
  - name: cicd
  - name: development
  - name: ingress-nginx
  - name: openfaas
  - name: openfaas-fn
```

The "default" namespace had been removed in https://github.com/frmscoe/AKS-helm/commit/ec52e9f663b449a86243de0781a8f1b11772ab18

### Actual behaviour

The "default" namespace still appears:

```
apiVersion: v2
description: A Helm chart for installing infrastructure components for the FRMS system.
name: infra-chart
type: application
version: 1.0.0

---
namespaces:
  - name: cicd
  - name: default
  - name: development
  - name: ingress-nginx
  - name: openfaas
  - name: openfaas-fn
```

### Proposed solution

Ensure that the update to the namespaces have pulled through properly.

The namespaces in the following binary still contains the "default" namespace as well: https://github.com/frmscoe/AKS-helm/blob/main/charts/infra-chart-1.0.0.tgz - I am not sure if this has an impact on the issue.
